name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: gcc 3_Implementation/day_v2.c 3_Implementation/day_v3.c 3_Implementation/test_validateDate.c 3_Implementation/unity/unity.c 3_Implementation/unity/unity.h -Iunity 
    
