name: Unit testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: gcc 3_Implementation/day_v2.c 3_Implementation/day_v3.c 3_Implementation/test_validateDate.c 3_Implementation/unity.c 3_Implementation/unity.h 3_Implementation/unity_internals.h
