/**
 * @file day.h
 * @author VIJAYA VARSHINI K
 * @brief Validating the day of the week, for a given date along with a message and a book suggession
 * @version 0.1
 * @date 2022-03-31
 * 
 * @copyright Copyright (c) 2022
 * 
 */




#SYNTAX
#Targetname : Dependant target name
#<TAB>Command


All:
	gcc day_v2.c day_v3.c test_validateDate.c unity/unity.c -Iunity 


Run:
	./a.exe